export const mockTableData = [
  {
    id: '#LX-0004',
    title: 'Tidal manifolds in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer luctus.',
    category: 'Design',
    status: 'Active',
    owner: 'Oren Vaske',
    priority: 'Normal',
    lastModified: '11 h ago',
  },
  {
    id: '#LX-0008',
    title: 'Synthetic lexicon in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi feugiat.',
    category: 'Ecology',
    status: 'Active',
    owner: 'Ada Vireo',
    priority: 'Low',
    lastModified: '12 h ago',
  },
  {
    id: '#LX-0012',
    title: 'Modular notation in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pretium.',
    category: 'Archive',
    status: 'Active',
    owner: 'Oren Vaske',
    priority: 'High',
    lastModified: '12 h ago',
  },
  {
    id: '#LX-0016',
    title: 'Recursive systems in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget.',
    category: 'Tech',
    status: 'Active',
    owner: 'Ada Vireo',
    priority: 'Normal',
    lastModified: '12 h ago',
  },
  {
    id: '#LX-0020',
    title: 'Quantum dynamics in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sed augue.',
    category: 'Research',
    status: 'Active',
    owner: 'Oren Vaske',
    priority: 'Low',
    lastModified: '12 h ago',
  },
  {
    id: '#LX-0024',
    title: 'Tidal manifolds in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae velit.',
    category: 'Design',
    status: 'Active',
    owner: 'Ada Vireo',
    priority: 'High',
    lastModified: '12 h ago',
  },
  {
    id: '#LX-0028',
    title: 'Distributed indexing in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti.',
    category: 'Logistics',
    status: 'Active',
    owner: 'Mila Corven',
    priority: 'Normal',
    lastModified: '13 h ago',
  },
  {
    id: '#LX-0032',
    title: 'Lateral memory in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet.',
    category: 'Operations',
    status: 'Active',
    owner: 'Noa Kester',
    priority: 'Low',
    lastModified: '13 h ago',
  },
  {
    id: '#LX-0036',
    title: 'Symbolic drift in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vulputate.',
    category: 'Research',
    status: 'Active',
    owner: 'Ada Vireo',
    priority: 'High',
    lastModified: '14 h ago',
  },
  {
    id: '#LX-0040',
    title: 'Temporal routing in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo.',
    category: 'Tech',
    status: 'Active',
    owner: 'Oren Vaske',
    priority: 'Normal',
    lastModified: '14 h ago',
  },
  {
    id: '#LX-0044',
    title: 'Adaptive context in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at feugiat.',
    category: 'Archive',
    status: 'Active',
    owner: 'Mila Corven',
    priority: 'Low',
    lastModified: '15 h ago',
  },
  {
    id: '#LX-0048',
    title: 'Synthetic lexicon in neural networks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tincidunt.',
    category: 'Ecology',
    status: 'Active',
    owner: 'Ada Vireo',
    priority: 'High',
    lastModified: '12 h ago',
  },
]
